# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./source/QDirect3D12Widget/d3dx12.h \
    ./source/QDirect3D12Widget/QDirect3D12Widget.h \
    ./header/Timer.h \
    ./header/SuikaGraphics.h
SOURCES += ./source/QDirect3D12Widget/QDirect3D12Widget.cpp \
    ./source/Utility/Timer.cpp \
    ./source/QtInterface/main.cpp \
    ./source/QtInterface/SuikaGraphics.cpp
FORMS += ./SuikaGraphics.ui
RESOURCES += SuikaGraphics.qrc
